version: '3'
services:
  apache:
    build: .docker/apache
    container_name: symfony_apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/symfony
    depends_on:
      - php

  php:
    build: .docker/php
    container_name: symfony_php
    volumes:
      - .:/home/wwwroot/symfony:cached
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: symfony_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql